name: Build and Test

on: 
  pull_request:
    branches:
     - main
     - develop

jobs:
  test:
    name: Build and Test
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: XCode setup
        uses: maxim-lobanov/setup-xcode@v1

      - name: Install Bundle
        run: bundle install

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Lizard
        run: pip install lizard

      - name: Install Sonar-Scanner
        run: brew install sonar-scanner
      
      - name: Install Swiftgen
        run: brew install swiftgen

      - name: Build and test
        run: bundle exec fastlane test sonar_login:"$SONAR_TOKEN"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}